name: Publish
on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: "npm install"
        run: |
          npm install
      
      - name: "Lerna Bootstrap"
        run: |
          npm run bootstrap
      
      - name: "Lerna Build"
        run: |
          npm run buildAffected

      - name: "Lerna Test"
        run: |
          npm run testAffected
